controller:
  extraArgs:
    - --leader-elect
  metrics:
    enabled: true
  replicas: 2

dashboard:
  enabled: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.20.0.52
    port: 80
    type: LoadBalancer
