resources:
  - resources/namespace.yml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 6.7.2 # https://artifacthub.io/packages/helm/argo/argo-cd?modal=changelog
    releaseName: argocd
    namespace: argo-system
    valuesFile: values.yml
    additionalValuesFiles:
      - values-notifications.yml
    includeCRDs: true
