configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    users.anonymous.enabled: "false"

crds:
  install: true
  keep:  false

global:
  revisionHistoryLimit: 3

applicationSet:
  metrics:
    enabled: true
  replicas: 2

controller:
  metrics:
    enabled: true

dex:
  metrics:
    enabled: true

redis-ha:
  enabled: true
  # https://github.com/argoproj/argo-cd/issues/11388
  haproxy:
    IPv6:
      enabled: false

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.20.0.49
    type: LoadBalancer
