controller:
  metricsConfig:
    enabled: true

server:
  autoscaling:
    enabled: true
  servicePort: 80
  serviceType: LoadBalancer
  serviceAnnotations:
    metallb.universe.tf/loadBalancerIPs: 10.20.0.53
